import React from 'react';
import App from './App.jsx';
import { renderToString } from 'react-dom/server';

export async function render(context) {
    const html = renderToString(<App url={context.url} />);
    const head = `<title>SSR Blog</title><meta name="description" content="Generated by Nuxc SSR">`;
    const state = { url: context.url, posts: 50 };
    return { html, head, state };
}
