/**
 * @nuce/plugin-auto-import — Auto-import APIs without manual imports
 * Replaces: unplugin-auto-import
 * Permissions: fs:write (generates .d.ts and .eslintrc)
 *
 * Scans source for usage of configured APIs and injects imports automatically.
 * Generates TypeScript global declarations and ESLint globals config.
 */

import fs from 'node:fs';
import path from 'node:path';

export type ImportPreset = 'vue' | 'vue-router' | 'pinia' | 'react' | 'vueuse';

export interface AutoImportOptions {
  /** Presets or custom import maps */
  imports: (ImportPreset | Record<string, string[]>)[];
  /** Path to generate .d.ts type declarations */
  dts?: string | false;
  /** ESLint globals config path or options */
  eslintrc?: { enabled: boolean; filepath?: string };
  /** Directories to scan for usage */
  dirs?: string[];
}

/** Built-in presets */
const PRESETS: Record<ImportPreset, Record<string, string[]>> = {
  vue: {
    vue: ['ref', 'computed', 'watch', 'watchEffect', 'reactive', 'readonly',
      'onMounted', 'onUnmounted', 'onBeforeMount', 'onUpdated', 'nextTick',
      'defineComponent', 'defineProps', 'defineEmits', 'defineExpose',
      'provide', 'inject', 'toRef', 'toRefs', 'isRef', 'unref', 'markRaw',
      'shallowRef', 'shallowReactive', 'effectScope'],
  },
  'vue-router': {
    'vue-router': ['useRouter', 'useRoute', 'createRouter', 'createWebHistory', 'createWebHashHistory'],
  },
  pinia: {
    pinia: ['defineStore', 'storeToRefs', 'acceptHMRUpdate'],
  },
  react: {
    react: ['useState', 'useEffect', 'useCallback', 'useMemo', 'useRef',
      'useContext', 'useReducer', 'useLayoutEffect', 'useId', 'useTransition',
      'createContext', 'forwardRef', 'memo', 'lazy', 'Suspense'],
  },
  vueuse: {
    '@vueuse/core': ['useLocalStorage', 'useSessionStorage', 'useMouse', 'useWindowSize',
      'useElementSize', 'useDark', 'useToggle', 'useClipboard', 'useEventListener',
      'useIntersectionObserver', 'useDebounceFn', 'useThrottleFn', 'useScrollLock',
      'useMediaQuery', 'useBreakpoints'],
  },
};

/** Resolve all import maps from options */
function resolveImports(imports: AutoImportOptions['imports']): Record<string, string[]> {
  const result: Record<string, string[]> = {};
  for (const item of imports) {
    if (typeof item === 'string') {
      const preset = PRESETS[item as ImportPreset];
      if (preset) Object.assign(result, preset);
    } else {
      Object.assign(result, item);
    }
  }
  return result;
}

export function autoImport(options: AutoImportOptions) {
  const { imports, dts = 'src/auto-imports.d.ts', eslintrc } = options;
  const importMap = resolveImports(imports);

  // Build reverse map: symbol → { from: package }
  const symbolMap: Record<string, string> = {};
  for (const [pkg, symbols] of Object.entries(importMap)) {
    for (const sym of symbols) symbolMap[sym] = pkg;
  }

  function generateDTS(): string {
    const lines = Object.entries(symbolMap).map(
      ([sym, pkg]) => `  const ${sym}: typeof import('${pkg}')['${sym}'];`
    );
    return `// Auto-generated by @nuce/plugin-auto-import\ndeclare global {\n${lines.join('\n')}\n}\nexport {};\n`;
  }

  function generateESLintRC(): string {
    const globals = Object.fromEntries(Object.keys(symbolMap).map((k) => [k, 'readonly']));
    return JSON.stringify({ globals }, null, 2);
  }

  return {
    name: '@nuce/plugin-auto-import',
    enforce: 'post' as const,

    configResolved(config: any) {
      const root = config.root ?? process.cwd();

      // Write .d.ts
      if (dts) {
        const dtsPath = path.resolve(root, dts);
        fs.mkdirSync(path.dirname(dtsPath), { recursive: true });
        fs.writeFileSync(dtsPath, generateDTS(), 'utf8');
      }

      // Write ESLint globals
      if (eslintrc?.enabled) {
        const eslintPath = path.resolve(root, eslintrc.filepath ?? '.eslintrc-auto-import.json');
        fs.writeFileSync(eslintPath, generateESLintRC(), 'utf8');
      }
    },

    transform(code: string, id: string) {
      if (!/\.(ts|tsx|js|jsx|vue|svelte)$/.test(id)) return;
      if (id.includes('node_modules')) return;

      const symbols = Object.keys(symbolMap);
      const usedSymbols = symbols.filter((sym) => {
        const re = new RegExp(`\\b${sym}\\b`);
        return re.test(code);
      });

      if (usedSymbols.length === 0) return;

      // Group used symbols by package
      const byPackage: Record<string, string[]> = {};
      for (const sym of usedSymbols) {
        const pkg = symbolMap[sym];
        if (!byPackage[pkg]) byPackage[pkg] = [];
        // check if already manually imported
        if (!code.includes(`from '${pkg}'`) && !code.includes(`from "${pkg}"`)) {
          byPackage[pkg].push(sym);
        }
      }

      const imports = Object.entries(byPackage)
        .filter(([, syms]) => syms.length > 0)
        .map(([pkg, syms]) => `import { ${syms.join(', ')} } from '${pkg}';`)
        .join('\n');

      if (!imports) return;

      return {
        code: imports + '\n' + code,
        map: null,
      };
    },
  };
}

export default autoImport;
