/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BuildCache {
  constructor(cachePath: string)
  get(key: string): string | null
  set(key: string, value: string): void
  delete(key: string): void
  has(key: string): boolean
  batchSet(entries: Record<string, string>): void
  clearTarget(target: string): number
  clearAll(): void
  getStats(): CacheStats
  compact(): void
  close(): void
}

/** Tokio-based build orchestrator */
export declare class BuildOrchestrator {
  /** Create a new orchestrator with specified parallelism */
  constructor(parallelism?: number | undefined | null)
  /** Log a build event */
  logEvent(stage: string, message: string, durationMs?: number | undefined | null): Promise<void>
  /** Get all logged events */
  getEvents(): Promise<Array<BuildEvent>>
  /** Clear all events */
  clearEvents(): Promise<void>
  /** Execute tasks in parallel */
  executeParallel(taskCount: number): Promise<OrchestratorStats>
  /** Process items in parallel using Rayon */
  processParallelSync(items: Array<string>): Array<string>
  /** Generate deterministic stable ID from content */
  generateStableId(content: string, prefix: string): string
  /** Batch generate stable IDs */
  batchGenerateIds(items: Array<string>, prefix: string): Array<string>
  /** Get orchestrator statistics */
  getStats(): Promise<OrchestratorStats>
  /** Get parallelism level */
  get parallelism(): number
  /** Shutdown the orchestrator */
  shutdown(): void
}

/**
 * High-performance graph analyzer using Integer-based Adjacency List
 * Uses string interning to map Strings <-> usize IDs for O(1) lookups and cache efficiency
 */
export declare class GraphAnalyzer {
  /** Create a new graph analyzer */
  constructor()
  /**
   * Batch add nodes to minimize NAPI bridge overhead
   * Format: ids list, and flat list of dependencies with counts
   * This avoids creating thousands of small arrays
   */
  addBatch(ids: Array<string>, edges: Array<Array<string>>): void
  /**
   * Detect circular dependencies using Iterative DFS
   * Uses explicit stack to avoid stack overflow on deep graphs (unlike JS recursion)
   */
  detectCycles(): Array<CircularDependency>
  /** Find orphaned nodes (not reachable from any entry point) */
  findOrphanedNodes(entryPoints: Array<string>): Array<string>
  /**
   * Native Tree Shaking: Get all reachable nodes from entry points
   * This is the "marked" set for building the final bundle
   */
  getReachableNodes(entryPoints: Array<string>): Array<string>
  /** Perform complete graph analysis */
  analyze(entryPoints: Array<string>): GraphAnalysisResult
  /** Topological sort using Kahn's algorithm */
  topologicalSort(): Array<string> | null
  /** Get node count */
  nodeCount(): number
  /** Get edge count */
  edgeCount(): number
  /** Clear all nodes */
  clear(): void
}

/**
 * Native file system watcher with 50ms debounce.
 *
 * Usage:
 *   const w = new NativeWatcher();
 *   w.start(['/path/to/watch'], (event) => { ... });
 *   ...
 *   w.stop();
 */
export declare class NativeWatcher {
  constructor()
  getVersion(): string
  /**
   * Start watching the given paths.
   * `callback` is called on every debounced file-system event.
   */
  start(paths: Array<string>, callback: (err: null | Error, event: WatchEvent) => void): void
  /** Stop watching and release all resources. */
  stop(): void
}

/** High-performance native worker for plugin transformations */
export declare class NativeWorker {
  /** Create a new native worker with specified pool size */
  constructor(poolSize?: number | undefined | null)
  /** Transform code using native SWC, LightningCSS, or Vue engine */
  transformSync(config: TransformConfig): TransformResult
  /** Parallel Transform: Process multiple modules across all cores */
  batchTransform(items: Array<TransformConfig>): Promise<Array<TransformResult>>
  /** Parallel Transform CSS: Process multiple CSS modules across all cores asynchronously */
  batchTransformCss(items: Array<TransformConfig>): Promise<Array<TransformResult>>
}

/** Batch hash multiple files (parallel processing in future) */
export declare function batchHash(contents: Array<string>): Array<string>

/** Benchmark graph operations */
export declare function benchmarkGraphAnalysis(nodeCount: number, edgeDensity: number): number

/** Benchmark parallel vs sequential processing */
export declare function benchmarkParallelism(itemCount: number): Record<string, number>

/** Benchmark function to compare performance */
export declare function benchmarkTransform(code: string, iterations: number): number

/** Build event for structured logging */
export interface BuildEvent {
  stage: string
  message: string
  timestamp: number
  durationMs?: number
  metadata?: string
}

/** Build stage for orchestration */
export declare const enum BuildStage {
  Init = 'Init',
  Graph = 'Graph',
  Plan = 'Plan',
  DeterminismCheck = 'DeterminismCheck',
  Execute = 'Execute',
  Emit = 'Emit'
}

export interface CacheStats {
  totalEntries: number
  hits: number
  misses: number
  hitRate: number
  sizeBytes: number
}

export interface ChunkerConfig {
  strategy: string
  maxChunkSizeKb: number
  entryPoints: Array<string>
}

export interface ChunkerResult {
  chunks: Array<ChunkOutput>
  eliminated: Array<string>
  totalModules: number
  liveModules: number
}

export interface ChunkOutput {
  hash: string
  modules: Array<string>
  isEntry: boolean
  sizeBytes: number
}

export interface CircularDependency {
  cycle: Array<string>
  entryPoint: string
}

export declare function createArtifactKey(artifactId: string, target: string): string

export declare function createGraphKey(graphHash: string): string

export declare function createInputKey(filePath: string, contentHash: string): string

export declare function createPlanKey(planHash: string, target: string): string

/**
 * Fast content hashing for cache keys
 * Uses XXH3 (ultra-fast non-cryptographic hash)
 */
export declare function fastHash(content: string): string

/** Helper function to get optimal parallelism */
export declare function getOptimalParallelism(): number

export interface GraphAnalysisResult {
  hasCycles: boolean
  cycles: Array<CircularDependency>
  orphanedNodes: Array<string>
  entryPoints: Array<string>
  totalNodes: number
  totalEdges: number
}

/**
 * Fast graph operations for dependency analysis
 *
 * Performance-critical operations implemented in Rust:
 * - Circular dependency detection (DFS-based, O(V+E))
 * - Topological sorting (Kahn's algorithm, O(V+E))
 * - Reachability analysis (BFS, O(V+E))
 * - Tree shaking (mark-and-sweep, O(V+E))
 */
export interface GraphNode {
  id: string
  dependencies: Array<string>
}

/** Simple function to test native bindings */
export declare function helloRust(): string

/**
 * Merge an ordered list of serialised source maps into a single map.
 *
 * Maps are applied left-to-right: the output of map[0] is the input of map[1], etc.
 *
 * N-API export (new, additive): mergeSourceMaps(maps: string[]): string
 */
export declare function mergeSourceMaps(maps: Array<string>): string

/** Global bundle minification pass */
export declare function minifySync(code: string): string

/** Fast string operations for module resolution */
export declare function normalizePath(path: string): string

export declare function zeptrChunk(graphJson: string, config: ChunkerConfig): ChunkerResult

/** Orchestrator statistics */
export interface OrchestratorStats {
  totalTasks: number
  completedTasks: number
  failedTasks: number
  totalDurationMs: number
  parallelism: number
}

/**
 * planBuild(manifest: string): TaskPlan
 *
 * manifest JSON schema:
 * {
 *   "swcVersion": "0.90.x",
 *   "cssVersion": "1.0.0-alpha.58",
 *   "configHash": "<xxh3 of zeptr.config>",
 *   "modules": [
 *     {
 *       "id": "abc123",
 *       "inputFiles": ["src/main.ts"],
 *       "inputHashes": ["<content hash>"],
 *       "outputs": ["dist/main.js"],
 *       "deps": ["dep-task-id"],
 *       "cachedHash": "<previously stored plan hash or empty>"
 *     }
 *   ]
 * }
 */
export declare function planBuild(manifestJson: string): TaskPlan

/**
 * Check or populate the pre-bundle cache for an array of module specifiers.
 *
 * `modules` is a JSON array of package metadata objects:
 *   [{ "name": "react", "version": "18.2.0", "deps": { ... } }, ...]
 *
 * Returns one PrebundleEntry per module — callers check `.hit` and
 * call the JS bundler only for misses, then persist with `prebundlePut`.
 *
 * N-API export (new, additive): prebundle(modules: string)
 */
export declare function prebundle(modulesJson: string, config: PrebundleConfig): Array<PrebundleEntry>

export interface PrebundleConfig {
  /** Path to .zeptr_cache directory */
  cacheRoot: string
}

export interface PrebundleEntry {
  moduleId: string
  /** SHA-256 fingerprint used as cache key */
  key: string
  /** Pre-bundled JS content */
  bundle: string
  /** true = cache hit, false = miss (caller must bundle and call put) */
  hit: boolean
}

/**
 * Persist a pre-bundled module into the cache after the JS bundler runs.
 *
 * N-API export (new, additive): prebundlePut(key, moduleId, bundle, config)
 */
export declare function prebundlePut(key: string, moduleId: string, bundle: string, config: PrebundleConfig): void

/**
 * Natively scan for imports/requires (Phase 4.2 Hot Path)
 * This is significantly faster than JS-based regex or full AST parsing
 */
export declare function scanImports(code: string): Array<string>

/**
 * Convenience standalone function: start watching paths and call callback on events.
 * Returns a handle ID (currently unused — call stop() on the NativeWatcher instance).
 */
export declare function startWatcher(paths: Array<string>, callback: (err: null | Error, event: WatchEvent) => void): void

export interface Task {
  /** Stable content-addressable ID */
  id: string
  /** The ID of the module this task belongs to */
  moduleId: string
  /** File hashes of all inputs (source files) */
  inputs: Array<string>
  /** Cache keys of expected outputs (artifact keys) */
  outputs: Array<string>
  /**
   * Hash of the transform function version used for this task.
   * SWC version + LightningCSS version + config hash.
   * When a dep upgrades, fn_hash changes → task auto-invalidates.
   */
  fnHash: string
  /** true = cache hit, skip transform */
  cached: boolean
}

export interface TaskPlan {
  /** Ordered list of tasks (topological, respecting deps) */
  tasks: Array<Task>
  /** Total number of tasks */
  total: number
  /** How many are already cached */
  cachedCount: number
  /** How many need executing */
  pendingCount: number
  /** Stable plan fingerprint (changes when ANY input or fn_hash changes) */
  planHash: string
}

export interface TransformConfig {
  path: string
  content: string
  loader: string
  minify?: boolean
}

export declare function transformCss(code: string, filename: string, minify: boolean): string

export declare function transformJs(code: string, filename: string, minify: boolean): string

export interface TransformResult {
  code: string
}

export interface WatchEvent {
  /** "create" | "modify" | "delete" | "rename" | "error" */
  kind: string
  /** Affected file paths */
  paths: Array<string>
  timestamp: number
}
