/**
 * GitHub Integration for Repro Dashboard
 * Handles creating issues from repro cases
 */

export interface GitHubConfig {
    token: string;
    owner: string;
    repo: string;
}

export interface IssueResult {
    success: boolean;
    url?: string;
    error?: string;
}

import { getFetch } from '../utils/fetch.js';

export class GitHubIntegration {
    private config: GitHubConfig;

    constructor(config: GitHubConfig) {
        this.config = config;
    }

    /**
     * Create a GitHub issue from a repro case
     */
    async createIssue(title: string, body: string, labels: string[] = []): Promise<IssueResult> {
        if (!this.config.token) {
            return { success: false, error: 'GitHub token not configured' };
        }

        try {
            const fetch = await getFetch();
            const response = await fetch(`https://api.github.com/repos/${this.config.owner}/${this.config.repo}/issues`, {
                method: 'POST',
                headers: {
                    'Authorization': `token ${this.config.token}`,
                    'Accept': 'application/vnd.github.v3+json',
                    'Content-Type': 'application/json',
                    'User-Agent': 'Zeptr-Build-Tool'
                },
                body: JSON.stringify({
                    title,
                    body,
                    labels: ['bug', 'repro', ...labels]
                })
            });

            if (!response.ok) {
                const error = await response.json();
                return {
                    success: false,
                    error: `GitHub API Error: ${error.message || response.statusText}`
                };
            }

            const data = await response.json();
            return {
                success: true,
                url: data.html_url
            };
        } catch (error) {
            return {
                success: false,
                error: error instanceof Error ? error.message : 'Unknown network error'
            };
        }
    }

    /**
     * Format repro case into issue markdown body
     */
    formatIssueBody(description: string, code: string, envInfo: any): string {
        return `
## Description
${description}

## Reproduction Code
\`\`\`js
${code}
\`\`\`

## Environment
- **OS**: ${envInfo.os || 'Unknown'}
- **Node**: ${envInfo.node || 'Unknown'}
- **Build Tool**: Zeptr

---
*Auto-generated by Zeptr Repro Dashboard*
        `.trim();
    }
}
